image: node:8
pipelines:
  branches:
    develop:
      - step:
          script:
            - yarn install
            - yarn global add code-push-cli
            - "sed -i -e 's/isDev: false/isDev: true/' config.js"
            - code-push login --accessKey 315aa6b8cba255ebec45808378c4d05f7d029789
            - code-push release-react EducareBox-Android android -d Develop --targetBinaryVersion "1.x.x" -desc develop_$BITBUCKET_BUILD_NUMBER --noDuplicateReleaseError
            - code-push release-react EducareBox-iOS ios -d Develop --targetBinaryVersion "1.x.x" -desc develop_$BITBUCKET_BUILD_NUMBER --noDuplicateReleaseError
  tags:
    ios-*:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn global add code-push-cli
            - code-push login --accessKey 315aa6b8cba255ebec45808378c4d05f7d029789
            - code-push release-react EducareBox-iOS ios --targetBinaryVersion 1.x.x --description `git describe --abbrev=0 --tags`
    android-*:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn global add code-push-cli
            - code-push login --accessKey 315aa6b8cba255ebec45808378c4d05f7d029789
            - code-push release-react EducareBox-Android android --targetBinaryVersion 1.x.x --description `git describe --abbrev=0 --tags`