image: node:8
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn global add code-push-cli
            - code-push login --accessKey 315aa6b8cba255ebec45808378c4d05f7d029789
            - code-push release-react EducareBox-iOS ios
            - code-push release-react EducareBox-Android android
