image: node:8
pipelines:
  branches:
    develop:
      - step:
          script:
            - yarn install
            - yarn global add code-push-cli
            - "sed -i -e 's/isDev: false/isDev: true/' config.js"
            - code-push login --accessKey 91002e2a343714875d64821314f8a30c5cbc7fa1
            - code-push release-react EducareBox-Android android -d Develop --targetBinaryVersion "*" --des develop_$BITBUCKET_BUILD_NUMBER --noDuplicateReleaseError
            - code-push release-react EducareBox-iOS ios -d Develop --targetBinaryVersion "*" --des develop_$BITBUCKET_BUILD_NUMBER --noDuplicateReleaseError
  tags:
    ios-*:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn global add code-push-cli
            - code-push login --accessKey 91002e2a343714875d64821314f8a30c5cbc7fa1
            - code-push release-react EducareBox-iOS ios --targetBinaryVersion 1.x.x --description $BITBUCKET_TAG
    android-*:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn global add code-push-cli
            - code-push login --accessKey 91002e2a343714875d64821314f8a30c5cbc7fa1
            - code-push release-react EducareBox-Android android --targetBinaryVersion 1.x.x --description $BITBUCKET_TAG