/* eslint-disable */
// flow-typed signature: d0407c4598b1dc09bbaf6f092f1df87c
// flow-typed version: <<STUB>>/git-hooks_v^1.1.8/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-hooks/lib/cli' {
  declare module.exports: any;
}

declare module 'git-hooks/lib/fs-helpers' {
  declare module.exports: any;
}

declare module 'git-hooks/lib/git-hooks' {
  declare module.exports: any;
}

declare module 'git-hooks/lib/hook-template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-hooks/lib/cli.js' {
  declare module.exports: $Exports<'git-hooks/lib/cli'>;
}
declare module 'git-hooks/lib/fs-helpers.js' {
  declare module.exports: $Exports<'git-hooks/lib/fs-helpers'>;
}
declare module 'git-hooks/lib/git-hooks.js' {
  declare module.exports: $Exports<'git-hooks/lib/git-hooks'>;
}
declare module 'git-hooks/lib/hook-template.js' {
  declare module.exports: $Exports<'git-hooks/lib/hook-template'>;
}
