// flow-typed signature: 434673599b5f582ee8aa7a8f7b177bd5
// flow-typed version: <<STUB>>/react-native-modal-datetime-picker_v^4.7.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modal-datetime-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modal-datetime-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modal-datetime-picker/src/CustomDatePickerAndroid/index' {
  declare module.exports: any;
}

declare module 'react-native-modal-datetime-picker/src/CustomDatePickerIOS/index' {
  declare module.exports: any;
}

declare module 'react-native-modal-datetime-picker/src/CustomDatePickerIOS/index.style' {
  declare module.exports: any;
}

declare module 'react-native-modal-datetime-picker/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modal-datetime-picker/src/CustomDatePickerAndroid/index.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src/CustomDatePickerAndroid/index'>;
}
declare module 'react-native-modal-datetime-picker/src/CustomDatePickerIOS/index.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src/CustomDatePickerIOS/index'>;
}
declare module 'react-native-modal-datetime-picker/src/CustomDatePickerIOS/index.style.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src/CustomDatePickerIOS/index.style'>;
}
declare module 'react-native-modal-datetime-picker/src/index.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src/index'>;
}
